"""
SOAR Pro — Incident Report Generator
Generates structured PDF reports for security incidents.

Report Contents:
  1. Alert Details (source, severity, title, description)
  2. Risk Score & Intent Analysis
  3. AI Analysis (explanation, recommended actions)
  4. Forensic Summary (evidence collected, integrity status)
  5. MITRE ATT&CK Mapping & Techniques
  6. Chain of Custody Summary
  7. Recommendations & Next Steps

Uses FPDF2 for PDF generation — lightweight, no system dependencies.
"""

import os
import json
import logging
from datetime import datetime, timezone
from typing import Dict, Any, Optional, List

from fpdf import FPDF

logger = logging.getLogger(__name__)

# ── Report storage ───────────────────────────────
REPORTS_DIR = os.getenv("REPORTS_DIR", "/app/reports")


class SOARReport(FPDF):
    """Custom FPDF class with SOAR Pro branding."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(20, 60, 120)
        self.cell(0, 10, "SOAR Pro - Incident Report", ln=True, align="C")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, "CONFIDENTIAL - For Authorized Personnel Only", ln=True, align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by SOAR Pro AI Service", align="C")

    def section_title(self, title: str):
        """Add a styled section header."""
        self.ln(4)
        self.set_fill_color(20, 60, 120)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def key_value(self, key: str, value: str, bold_key: bool = True):
        """Add a key-value pair line."""
        self.set_x(10)
        self.set_font("Helvetica", "B" if bold_key else "", 10)
        key_width = 45
        self.cell(key_width, 6, f"{key}:", align="L")
        self.set_font("Helvetica", "", 10)
        w = 190 - 10 - key_width
        self.multi_cell(w, 6, str(value) if value else "N/A", align="L")

    def severity_badge(self, severity: str):
        """Add a colored severity indicator."""
        colors = {
            "critical": (220, 30, 30),
            "high": (230, 120, 0),
            "medium": (200, 180, 0),
            "low": (60, 160, 60),
        }
        r, g, b = colors.get(severity.lower(), (128, 128, 128))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10)
        self.cell(25, 7, f" {severity.upper()} ", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def bullet_list(self, items: list):
        """Add a bulleted list."""
        self.set_font("Helvetica", "", 10)
        for item in items:
            self.set_x(20)
            self.multi_cell(170, 6, f"*  {item}", align="L")


class ReportGenerator:
    """Generates PDF incident reports from alert data, AI analysis, and forensic results."""

    async def generate(
        self,
        incident_id: str,
        alert_data: Dict[str, Any],
        ai_analysis: Dict[str, Any],
        forensic_summary: Optional[Dict[str, Any]] = None,
        mitre_techniques: Optional[List[str]] = None,
        db_pool=None,
    ) -> Dict[str, Any]:
        """
        Generate a complete PDF incident report.

        Returns: {"report_path": str, "report_id": str, "pages": int}
        """
        os.makedirs(REPORTS_DIR, exist_ok=True)

        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        report_filename = f"incident_{incident_id}_{timestamp}.pdf"
        report_path = os.path.join(REPORTS_DIR, report_filename)

        pdf = SOARReport()
        pdf.alias_nb_pages()
        pdf.add_page()

        # ── 1. Report Header ────────────────────
        self._add_report_header(pdf, incident_id)

        # ── 2. Alert Details ─────────────────────
        self._add_alert_details(pdf, alert_data)

        # ── 3. Risk Score ────────────────────────
        self._add_risk_score(pdf, alert_data, ai_analysis)

        # ── 4. AI Analysis ───────────────────────
        self._add_ai_analysis(pdf, ai_analysis)

        # ── 5. MITRE ATT&CK ─────────────────────
        if mitre_techniques or ai_analysis.get("mitre_explanation"):
            self._add_mitre_section(pdf, mitre_techniques, ai_analysis)

        # ── 6. Forensic Summary ──────────────────
        if forensic_summary:
            self._add_forensic_summary(pdf, forensic_summary)

        # ── 7. Recommendations ───────────────────
        self._add_recommendations(pdf, ai_analysis)

        # ── 8. Report Footer/Metadata ────────────
        self._add_report_metadata(pdf, incident_id)

        # Save
        pdf.output(report_path)

        logger.info(f"Report generated: {report_filename}")

        # Log to database
        if db_pool:
            try:
                async with db_pool.acquire() as conn:
                    await conn.execute("""
                        INSERT INTO reports (name, type, format, status, file_path, file_size)
                        VALUES ($1, 'incident', 'pdf', 'completed', $2, $3)
                    """, f"Incident Report - {incident_id}", report_path,
                    os.path.getsize(report_path))
            except Exception as e:
                logger.warning(f"Report DB logging failed: {e}")

        return {
            "report_path": report_path,
            "report_filename": report_filename,
            "incident_id": incident_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "pages": pdf.page_no(),
        }

    # ── Section builders ─────────────────────────

    def _add_report_header(self, pdf: SOARReport, incident_id: str):
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, f"Incident ID: {incident_id}", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Report Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}", ln=True)
        pdf.cell(0, 6, f"Classification: CONFIDENTIAL", ln=True)
        pdf.ln(3)

    def _add_alert_details(self, pdf: SOARReport, alert: Dict):
        pdf.section_title("1. ALERT DETAILS")

        # Severity badge
        severity = alert.get("severity", "unknown")
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 6, "Severity:")
        pdf.severity_badge(severity)
        pdf.ln(3)

        pdf.key_value("Title", alert.get("title", "N/A"))
        pdf.key_value("Source", alert.get("source", alert.get("source_name", "N/A")))
        pdf.key_value("Category", alert.get("category", "N/A"))
        pdf.key_value("Status", alert.get("status", "N/A"))
        pdf.key_value("Received At", alert.get("received_at", "N/A"))

        desc = alert.get("description", "")
        if desc:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Description:", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, desc[:1000])

        # IOCs
        indicators = alert.get("indicators", {})
        if any(indicators.get(k) for k in indicators):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Indicators of Compromise (IOCs):", ln=True)
            pdf.set_font("Courier", "", 9)
            for ioc_type, values in indicators.items():
                if values:
                    for val in (values if isinstance(values, list) else [values]):
                        pdf.set_x(20)
                        pdf.cell(0, 5, f"{ioc_type}: {val}", ln=True)

    def _add_risk_score(self, pdf: SOARReport, alert: Dict, analysis: Dict):
        pdf.section_title("2. RISK ASSESSMENT")

        risk_score = alert.get("risk_score", 0)
        pdf.set_font("Helvetica", "B", 16)
        if risk_score >= 80:
            pdf.set_text_color(220, 30, 30)
        elif risk_score >= 60:
            pdf.set_text_color(230, 120, 0)
        else:
            pdf.set_text_color(60, 160, 60)
        pdf.cell(0, 10, f"Risk Score: {risk_score} / 100", ln=True)
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Helvetica", "", 10)
        risk_interp = analysis.get("risk_interpretation", "")
        if risk_interp:
            pdf.multi_cell(0, 6, risk_interp)

        pdf.ln(2)
        pdf.set_font("Helvetica", "I", 9)
        pdf.multi_cell(0, 5, "Formula: Risk Score = Severity x Asset Criticality x Threat Confidence (normalized to 0-100)")

    def _add_ai_analysis(self, pdf: SOARReport, analysis: Dict):
        pdf.section_title("3. AI ANALYSIS")

        method = analysis.get("analysis_method", "unknown")
        confidence = analysis.get("ai_confidence", 0)
        pdf.key_value("Analysis Method", f"{'Google Gemini AI' if method == 'gemini' else 'Rule-Based Engine'}")
        pdf.key_value("AI Confidence", f"{confidence:.0%}")
        pdf.ln(2)

        explanation = analysis.get("explanation", "")
        if explanation:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Explanation:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, explanation)

        summary = analysis.get("incident_summary", "")
        if summary:
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Incident Summary:", ln=True)
            pdf.set_font("Courier", "", 9)
            pdf.multi_cell(0, 5, summary[:2000])

    def _add_mitre_section(self, pdf: SOARReport, techniques: Optional[List[str]], analysis: Dict):
        pdf.section_title("4. MITRE ATT&CK MAPPING")

        if techniques:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Mapped Techniques:", ln=True)
            pdf.set_font("Courier", "", 9)
            for tech in techniques[:10]:
                from mitre_knowledge import get_technique_explanation
                info = get_technique_explanation(tech)
                pdf.set_x(20)
                pdf.multi_cell(170, 5, f"{tech} - {info['name']}: {info['description']}", align="L")

        mitre_exp = analysis.get("mitre_explanation")
        if mitre_exp:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "AI MITRE Analysis:", ln=True)
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, mitre_exp)

    def _add_forensic_summary(self, pdf: SOARReport, forensic: Dict):
        pdf.section_title("5. FORENSIC EVIDENCE SUMMARY")

        pdf.key_value("Status", forensic.get("status", "N/A").upper())
        pdf.key_value("Integrity", forensic.get("overall_integrity", "N/A"))
        pdf.key_value("Evidence Count", str(forensic.get("evidence_count", 0)))
        pdf.key_value("Chain Hash", forensic.get("chain_hash_stored", "N/A"))
        pdf.key_value("Collected At", forensic.get("collected_at", "N/A"))

        files = forensic.get("files", [])
        if files:
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Evidence Files:", ln=True)
            pdf.set_font("Courier", "", 9)
            for f in files:
                status = f.get("status", "UNKNOWN")
                icon = "PASS" if status == "VERIFIED" else "FAIL"
                pdf.set_x(20)
                pdf.cell(0, 5, f"[{icon}] {f['file']} - {f.get('stored_hash', 'N/A')}", ln=True)

    def _add_recommendations(self, pdf: SOARReport, analysis: Dict):
        pdf.section_title("6. RECOMMENDED ACTIONS")

        actions = analysis.get("recommended_actions", [])
        if actions:
            for i, action in enumerate(actions, 1):
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_x(15)
                pdf.cell(8, 6, f"{i}.")
                pdf.set_font("Helvetica", "", 10)
                pdf.set_x(25)
                pdf.multi_cell(165, 6, action, align="L")
        else:
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(0, 6, "No specific recommendations generated.", ln=True)

    def _add_report_metadata(self, pdf: SOARReport, incident_id: str):
        pdf.ln(10)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(128, 128, 128)
        pdf.multi_cell(0, 4,
            f"This report was automatically generated by the SOAR Pro AI Service.\n"
            f"Document Classification: CONFIDENTIAL\n"
            f"Incident Reference: {incident_id}\n"
            f"Generation Timestamp: {datetime.now(timezone.utc).isoformat()}\n"
            f"Integrity: This report should be verified against the evidence chain hash.\n"
            f"Standard: Aligned with NIST SP 800-61 Incident Handling Guide"
        )
